[package]
name = "a_beautiful_year"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "a_beautiful_year"
path = "src/a_beautiful_year.rs"